pretrained_base_model_path: "./pretrained_weights/stable-diffusion-v1-5/"
pretrained_vae_path: "./pretrained_weights/sd-vae-ft-mse"
image_encoder_path: "./pretrained_weights/image_encoder"
denoising_unet_path: "./exp_output/stage1/denoising_unet-10000.pth"
reference_unet_path: "./exp_output/stage1/reference_unet-10000.pth"
pose_guider_path: "./exp_output/stage1/pose_guider-10000.pth"
motion_module_path: "./pretrained_weights/motion_module.pth"

inference_config: "./configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'

test_cases:
  [
    "test_videos/bird1.mp4",
    "test_videos/bird2.mp4",
    "test_videos/horse1.mp4",
    "test_videos/horse2.mp4",
    "test_videos/guiter1.mp4",
    "test_videos/guiter2.mp4",
]

